GH-19  Video Teaser V1.4
HWR-Berlin-SWE-II-Gruppe-2-Team-3-2022/Dokumentation pull request #23
Opened 2022-02-27 12:32 UTC by dashvogel

Youtube Link ist in der txt Datei.
Um die mp4 kümmere ich mich wenn die finale Version fertig ist.

(bitte "Unused Slides" ignorieren)

2022-02-28 10:14 UTC, MK2112 requested changes
- [x] Teaser muss noch 10 Sekunden gestreckt werden -> 2 min

- [x] 1:43 - Outdated Screenshot. Das mit der Sprachauswahl ist ja nicht mehr Teil von Equaly, auch gibt es keine Auswahl des Gendering-Stils.

- [ ] 0:15 - "That Helps You By Gendering Your Texts Correctly" -> "It Helps You By Gendering ..."

- [ ] 1:00 - "An AI for Language Tagging (neuer Stichpunkt) Tokenizing and POSTagging" --> Aus den zwei Stichpunkten einen machen, aus "AI" "AI Pipeline" machen

- [ ] 1:00 - "A database filled with words" -> "A dictionary database for word replacements"

- [ ] 1:13 - Da muss ein konkretes Beispiel zu genderbarem Text "reinanimiert" werden. So z.B. "All men need to know about this invention" und "All people need to know about this invention"

- [ ] 1:20 - Da steht ja schon ein Beispiel in der Equaly-UI drin --> raus damit, durch das in 1:13 gezeigte Beispiel (das muss dann hier wohl auch reinanimiert werden) ersetzen (damit wird das konsistenter)

2022-02-28 18:50 UTC, MK2112 requested changes
0:36 - "WHOS" -> "WHO'S"
0:42 - "IT'S FOR" -> "BUILT FOR"
0:42 - "WRITERS" -> "AUTHORS"

(vielleicht noch irgendwas zur Einfachheit der Ausführbarkeit (nur eine JAR-Datei), damit wir die 2:00 voll bekommen)

2022-03-09 01:54 UTC, FeliTheCat reviewed
- Text für den Teaser auf neusten Stand bringen
- veraltete Dateien löschen
- evtl. Screenshots auf neuesten Stand bringen (0:29, 1:38ff)
- Vorschlag: den Teil "How to find Equaly?" direkt hinter "Who is Equaly for?" verschieben, danach folgt "How to use Equaly?" (muss aber nicht sein)

Ansonsten :FelixApproved:

2022-03-09 19:04 UTC, MK2112 approved these changes

2022-03-10 10:35 UTC, FeliTheCat requested changes
Der Link zum Video muss noch in die pdf

2022-03-10 12:37 UTC, FeliTheCat approved these changes

2022-03-10 12:38 UTC, merged